version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: release-it
    versions:
    - 14.3.0
    - 14.4.0
    - 14.4.1
    - 14.5.0
    - 14.5.1
  - dependency-name: qs
    versions:
    - 6.10.0
    - 6.10.1
